const constants = {
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILURE:"LOGIN_FAILURE",
	FILTER_CHANGE:"FILTER_CHANGE",
	REMOVE_FILTER:"REMOVE_FILTER",
	ADD_ITEM_TO_CART:"ADD_ITEM_TO_CART",
	REMOVE_ITEMS_FROM_CART:"REMOVE_ITEMS_FROM_CART"
}
export default constants;
